name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi-app
            git reset --hard origin/main  # Ensure latest code
            git pull origin main
            
            # Activate virtual environment and update dependencies
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            
            # Restart FastAPI with error handling
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi
            sudo systemctl status fastapi --no-pager || journalctl -u fastapi --no-pager | tail -n 20

            # Restart and validate Nginx
            sudo systemctl restart nginx
            sudo nginx -t
            sudo systemctl reload nginx
